In [1]:
#Подключение необходимых библиотеки
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
#Читаем файл, выводим информацию о файле для дальнейшей обработки. Первое, что нужно обработать: 
#столбец ApplicationDate и категориальные признаки
df = pd.read_csv('train.csv')
df_info = df.info()
df_head = df.head()
df_info, df_head

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11017 entries, 0 to 11016
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ApplicationDate             10487 non-null  object
 1   Age                         10487 non-null  float64
 2   AnnualIncome                10487 non-null  float64
 3   CreditScore                 9986 non-null   float64
 4   LoanAmount                  9986 non-null   float64
 5   LoanDuration                10487 non-null  float64
 6   MaritalStatus               10487 non-null  object
 7   NumberOfDependents          10487 non-null  float64
 8   HomeOwnershipStatus         10487 non-null  object
 9   MonthlyDebtPayments         9986 non-null   float64
 10  CreditCardUtilizationRate   10487 non-null  float64
 11  NumberOfOpenCreditLines     10487 non-null  float64
 12  NumberOfCreditInquiries     10487 non-null  float64
 13  DebtToIncomeRatio           10487 non-null  float64
 14  BankruptcyHistory           9986 non-null   float64
 15  LoanPurpose                 9986 non-null   object
 16  PreviousLoanDefaults        10487 non-null  float64
 17  PaymentHistory              10487 non-null  float64
 18  LengthOfCreditHistory       10487 non-null  float64
 19  SavingsAccountBalance       10487 non-null  float64
 20  CheckingAccountBalance      9986 non-null   float64
 21  TotalAssets                 9986 non-null   float64
 22  TotalLiabilities            10487 non-null  float64
 23  MonthlyIncome               10487 non-null  float64
 24  UtilityBillsPaymentHistory  10487 non-null  float64
 25  JobTenure                   10487 non-null  float64
 26  EmploymentStatus            10487 non-null  object
 27  EducationLevel              10487 non-null  object
 28  Experience                  10487 non-null  float64
 29  NetWorth                    9986 non-null   float64
 30  BaseInterestRate            9986 non-null   float64
 31  InterestRate                10487 non-null  float64
 32  MonthlyLoanPayment          10487 non-null  float64
 33  TotalDebtToIncomeRatio      10487 non-null  float64
 34  LoanApproved                10487 non-null  float64
 35  RiskScore                   10487 non-null  float64
dtypes: float64(30), object(6)
memory usage: 3.0+ MB

(None,
   ApplicationDate   Age  AnnualIncome  CreditScore  LoanAmount  LoanDuration  \
 0      2010-06-26  27.0       66829.0        549.0     17290.0          60.0
 1      1996-09-23  55.0      172147.0        850.0     16110.0          36.0
 2      2015-01-19  51.0      300000.0        850.0     38436.0          36.0
 3      1981-05-12  25.0       34683.0        847.0     19186.0          48.0
 4      1995-05-07  55.0      300000.0        850.0     30437.0          48.0

   MaritalStatus  NumberOfDependents HomeOwnershipStatus  MonthlyDebtPayments  \
 0      Divorced                 1.0                Rent               1095.0
 1       Widowed                 1.0            Mortgage                211.0
 2       Married                 0.0            Mortgage                546.0
 3       Married                 0.0               Other                153.0
 4        Single                 2.0                Rent                562.0

    ...  EmploymentStatus  EducationLevel  Experience  NetWorth  \
 0  ...          Employed       Associate         4.0   35067.0
 1  ...          Employed     High School        33.0   27001.0
 2  ...          Employed        Bachelor        28.0  278382.0
 3  ...          Employed     High School         0.0    9224.0
 4  ...          Employed        Bachelor        31.0    4502.0

    BaseInterestRate InterestRate  MonthlyLoanPayment  TotalDebtToIncomeRatio  \
 0          0.257790     0.251465          508.970230                0.288013
 1          0.086110     0.093173          514.675859                0.050585
 2          0.108436     0.115443         1268.276385                0.072571
 3          0.100686     0.112822          498.505187                0.225415
 4          0.110437     0.089037          756.035156                0.052721

    LoanApproved  RiskScore
 0           0.0  66.176500
 1           1.0  28.495737
 2           1.0  34.488104
 3           1.0  36.910753
 4           1.0  31.347091

 [5 rows x 36 columns])

In [3]:
# Конвертируем ApplicationDate в формат datetime и разбиваем на 3 столбца: год, месяц и день
df['ApplicationDate'] = pd.to_datetime(df['ApplicationDate'], errors='coerce')
df['ApplicationYear'] = df['ApplicationDate'].dt.year
df['ApplicationMonth'] = df['ApplicationDate'].dt.month
df['ApplicationDay'] = df['ApplicationDate'].dt.day

# Удаляем исходный столбец
df = df.drop(columns=['ApplicationDate'])
df

,Age,AnnualIncome,CreditScore,LoanAmount,LoanDuration,MaritalStatus,NumberOfDependents,HomeOwnershipStatus,MonthlyDebtPayments,CreditCardUtilizationRate,...,NetWorth,BaseInterestRate,InterestRate,MonthlyLoanPayment,TotalDebtToIncomeRatio,LoanApproved,RiskScore,ApplicationYear,ApplicationMonth,ApplicationDay
0,27.0,66829.0,549.0,17290.0,60.0,Divorced,1.0,Rent,1095.0,0.151985,...,35067.0,0.257790,0.251465,508.970230,0.288013,0.0,66.176500,2010.0,6.0,26.0
1,55.0,172147.0,850.0,16110.0,36.0,Widowed,1.0,Mortgage,211.0,0.175693,...,27001.0,0.086110,0.093173,514.675859,0.050585,1.0,28.495737,1996.0,9.0,23.0
2,51.0,300000.0,850.0,38436.0,36.0,Married,0.0,Mortgage,546.0,0.444605,...,278382.0,0.108436,0.115443,1268.276385,0.072571,1.0,34.488104,2015.0,1.0,19.0
3,25.0,34683.0,847.0,19186.0,48.0,Married,0.0,Other,153.0,0.188452,...,9224.0,0.100686,0.112822,498.505187,0.225415,1.0,36.910753,1981.0,5.0,12.0
4,55.0,300000.0,850.0,30437.0,48.0,Single,2.0,Rent,562.0,0.273431,...,4502.0,0.110437,0.089037,756.035156,0.052721,1.0,31.347091,1995.0,5.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11012,57.0,300000.0,850.0,14756.0,48.0,Married,2.0,Own,620.0,0.477742,...,167544.0,0.094756,0.106387,378.792448,0.039952,1.0,32.440586,2010.0,7.0,10.0
11013,28.0,15000.0,300.0,51361.0,96.0,Single,1.0,Own,696.0,0.322554,...,116879.0,0.446361,0.401087,1793.042130,1.991234,0.0,67.673170,2003.0,10.0,22.0
11014,23.0,15000.0,302.0,30724.0,72.0,Married,3.0,Rent,413.0,0.497062,...,250778.0,0.404724,0.360670,1047.672294,1.168538,0.0,75.292707,1983.0,5.0,12.0
11015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11016,41.0,300000.0,NaN,NaN,60.0,Single,2.0,Own,NaN,0.273345,...,NaN,NaN,0.111351,513.709256,0.040548,1.0,32.805455,2000.0,1.0,7.0

In [4]:
#Выводим список категориальных признаков
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
categorical_cols

['MaritalStatus',
 'HomeOwnershipStatus',
 'LoanPurpose',
 'EmploymentStatus',
 'EducationLevel']

In [5]:
#Применяем One-hot encoding категориальных признаков
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [6]:
print(df.shape)

(11017, 49)

In [7]:
df

,Age,AnnualIncome,CreditScore,LoanAmount,LoanDuration,NumberOfDependents,MonthlyDebtPayments,CreditCardUtilizationRate,NumberOfOpenCreditLines,NumberOfCreditInquiries,...,LoanPurpose_Debt Consolidation,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,EmploymentStatus_Self-Employed,EmploymentStatus_Unemployed,EducationLevel_Bachelor,EducationLevel_Doctorate,EducationLevel_High School,EducationLevel_Master
0,27.0,66829.0,549.0,17290.0,60.0,1.0,1095.0,0.151985,2.0,1.0,...,False,True,False,False,False,False,False,False,False,False
1,55.0,172147.0,850.0,16110.0,36.0,1.0,211.0,0.175693,3.0,0.0,...,False,False,True,False,False,False,False,False,True,False
2,51.0,300000.0,850.0,38436.0,36.0,0.0,546.0,0.444605,3.0,0.0,...,False,True,False,False,False,False,True,False,False,False
3,25.0,34683.0,847.0,19186.0,48.0,0.0,153.0,0.188452,7.0,0.0,...,True,False,False,False,False,False,False,False,True,False
4,55.0,300000.0,850.0,30437.0,48.0,2.0,562.0,0.273431,3.0,1.0,...,True,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11012,57.0,300000.0,850.0,14756.0,48.0,2.0,620.0,0.477742,1.0,3.0,...,False,True,False,False,False,False,False,False,False,False
11013,28.0,15000.0,300.0,51361.0,96.0,1.0,696.0,0.322554,2.0,0.0,...,False,False,True,False,False,False,True,False,False,False
11014,23.0,15000.0,302.0,30724.0,72.0,3.0,413.0,0.497062,2.0,0.0,...,False,True,False,False,True,False,False,False,False,False
11015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
11016,41.0,300000.0,NaN,NaN,60.0,2.0,NaN,0.273345,2.0,2.0,...,False,False,False,False,False,False,False,False,True,False

In [8]:
# Удаляем дубликаты
df = df.drop_duplicates()
df.shape

(10001, 49)

In [9]:
# Функция для обнаружения выбросов с использованием метода IQR и их удаления
def remove_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    # Удаляем строки, где значения находятся за пределами допустимого диапазона
    data_cleaned = data[(data[column] >= lower_bound) & (data[column] <= upper_bound)]
    return data_cleaned

# Удаление выбросов в столбце RiskScore
df = remove_outliers_iqr(df, 'RiskScore')
df.shape

(9788, 49)

In [10]:
# Просмотр количества пропусков в каждом столбце
missing_values = df.isnull().sum()

# Заполнение пропусков медианой или средним для числовых признаков
df.fillna(df.median(), inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9788 entries, 0 to 9999
Data columns (total 49 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             9788 non-null   float64
 1   AnnualIncome                    9788 non-null   float64
 2   CreditScore                     9788 non-null   float64
 3   LoanAmount                      9788 non-null   float64
 4   LoanDuration                    9788 non-null   float64
 5   NumberOfDependents              9788 non-null   float64
 6   MonthlyDebtPayments             9788 non-null   float64
 7   CreditCardUtilizationRate       9788 non-null   float64
 8   NumberOfOpenCreditLines         9788 non-null   float64
 9   NumberOfCreditInquiries         9788 non-null   float64
 10  DebtToIncomeRatio               9788 non-null   float64
 11  BankruptcyHistory               9788 non-null   float64
 12  PreviousLoanDefaults            9788 non-null   float64
 13  PaymentHistory                  9788 non-null   float64
 14  LengthOfCreditHistory           9788 non-null   float64
 15  SavingsAccountBalance           9788 non-null   float64
 16  CheckingAccountBalance          9788 non-null   float64
 17  TotalAssets                     9788 non-null   float64
 18  TotalLiabilities                9788 non-null   float64
 19  MonthlyIncome                   9788 non-null   float64
 20  UtilityBillsPaymentHistory      9788 non-null   float64
 21  JobTenure                       9788 non-null   float64
 22  Experience                      9788 non-null   float64
 23  NetWorth                        9788 non-null   float64
 24  BaseInterestRate                9788 non-null   float64
 25  InterestRate                    9788 non-null   float64
 26  MonthlyLoanPayment              9788 non-null   float64
 27  TotalDebtToIncomeRatio          9788 non-null   float64
 28  LoanApproved                    9788 non-null   float64
 29  RiskScore                       9788 non-null   float64
 30  ApplicationYear                 9788 non-null   float64
 31  ApplicationMonth                9788 non-null   float64
 32  ApplicationDay                  9788 non-null   float64
 33  MaritalStatus_Married           9788 non-null   bool
 34  MaritalStatus_Single            9788 non-null   bool
 35  MaritalStatus_Widowed           9788 non-null   bool
 36  HomeOwnershipStatus_Other       9788 non-null   bool
 37  HomeOwnershipStatus_Own         9788 non-null   bool
 38  HomeOwnershipStatus_Rent        9788 non-null   bool
 39  LoanPurpose_Debt Consolidation  9788 non-null   bool
 40  LoanPurpose_Education           9788 non-null   bool
 41  LoanPurpose_Home                9788 non-null   bool
 42  LoanPurpose_Other               9788 non-null   bool
 43  EmploymentStatus_Self-Employed  9788 non-null   bool
 44  EmploymentStatus_Unemployed     9788 non-null   bool
 45  EducationLevel_Bachelor         9788 non-null   bool
 46  EducationLevel_Doctorate        9788 non-null   bool
 47  EducationLevel_High School      9788 non-null   bool
 48  EducationLevel_Master           9788 non-null   bool
dtypes: bool(16), float64(33)
memory usage: 2.7 MB

In [11]:
# Определение числовых признаков
numeric_cols = df.select_dtypes(include=['float64', 'int64']).columns
numeric_cols = numeric_cols.difference(['RiskScore'])

scaler = StandardScaler()

# Нормализация числовых признаков
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])
df

,Age,AnnualIncome,CreditScore,LoanAmount,LoanDuration,NumberOfDependents,MonthlyDebtPayments,CreditCardUtilizationRate,NumberOfOpenCreditLines,NumberOfCreditInquiries,...,LoanPurpose_Debt Consolidation,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,EmploymentStatus_Self-Employed,EmploymentStatus_Unemployed,EducationLevel_Bachelor,EducationLevel_Doctorate,EducationLevel_High School,EducationLevel_Master
0,-1.109492,-0.559559,-0.765523,-0.454457,0.271183,-0.398582,1.126794,-0.833001,-0.593616,0.020545,...,False,True,False,False,False,False,False,False,False,False
1,1.307421,0.350110,0.991248,-0.498615,-0.709908,-0.398582,-0.668085,-0.684002,-0.018223,-0.989991,...,False,False,True,False,False,False,False,False,True,False
2,0.962147,1.454421,0.991248,0.336864,-0.709908,-1.103301,0.012101,1.006093,-0.018223,-0.989991,...,False,True,False,False,False,False,True,False,False,False
3,-1.282128,-0.837215,0.973739,-0.383505,-0.219362,-1.103301,-0.785849,-0.603812,2.283346,-0.989991,...,True,False,False,False,False,False,False,False,True,False
4,1.307421,1.454421,0.991248,0.037527,-0.219362,0.306137,0.044587,-0.069722,-0.018223,0.020545,...,True,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,-1.109492,-1.007224,-1.862775,-0.371568,-0.709908,-0.398582,0.166412,0.784898,-0.593616,0.020545,...,False,True,False,False,False,False,False,False,True,False
9996,0.789511,0.461834,-0.625448,-0.822799,1.252275,-1.103301,0.824264,-1.188470,-1.744400,-0.989991,...,False,False,False,False,False,False,False,False,True,False
9997,1.307421,1.426159,0.991248,0.551141,1.252275,0.306137,-0.123936,0.561112,1.707953,-0.989991,...,False,True,False,False,False,False,False,False,True,False
9998,-0.591582,0.644902,0.250019,-0.285161,-1.200454,-1.103301,-0.286369,-1.342785,0.557169,-0.989991,...,False,False,False,False,True,False,False,False,True,False
9999,-1.023173,-0.383262,-0.181878,-0.543858,-1.691000,1.010855,-0.787879,-1.249973,-1.169008,-0.989991,...,False,False,False,False,False,False,True,False,False,False

In [12]:
# Создание scaler для RiskScore
scaler_risk = StandardScaler()

# Нормализация RiskScore в тренировочном наборе
df['RiskScore'] = scaler_risk.fit_transform(df[['RiskScore']])

In [13]:
X = df.drop('RiskScore', axis=1)
y = df['RiskScore']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [15]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7830 entries, 3646 to 7434
Data columns (total 48 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             7830 non-null   float64
 1   AnnualIncome                    7830 non-null   float64
 2   CreditScore                     7830 non-null   float64
 3   LoanAmount                      7830 non-null   float64
 4   LoanDuration                    7830 non-null   float64
 5   NumberOfDependents              7830 non-null   float64
 6   MonthlyDebtPayments             7830 non-null   float64
 7   CreditCardUtilizationRate       7830 non-null   float64
 8   NumberOfOpenCreditLines         7830 non-null   float64
 9   NumberOfCreditInquiries         7830 non-null   float64
 10  DebtToIncomeRatio               7830 non-null   float64
 11  BankruptcyHistory               7830 non-null   float64
 12  PreviousLoanDefaults            7830 non-null   float64
 13  PaymentHistory                  7830 non-null   float64
 14  LengthOfCreditHistory           7830 non-null   float64
 15  SavingsAccountBalance           7830 non-null   float64
 16  CheckingAccountBalance          7830 non-null   float64
 17  TotalAssets                     7830 non-null   float64
 18  TotalLiabilities                7830 non-null   float64
 19  MonthlyIncome                   7830 non-null   float64
 20  UtilityBillsPaymentHistory      7830 non-null   float64
 21  JobTenure                       7830 non-null   float64
 22  Experience                      7830 non-null   float64
 23  NetWorth                        7830 non-null   float64
 24  BaseInterestRate                7830 non-null   float64
 25  InterestRate                    7830 non-null   float64
 26  MonthlyLoanPayment              7830 non-null   float64
 27  TotalDebtToIncomeRatio          7830 non-null   float64
 28  LoanApproved                    7830 non-null   float64
 29  ApplicationYear                 7830 non-null   float64
 30  ApplicationMonth                7830 non-null   float64
 31  ApplicationDay                  7830 non-null   float64
 32  MaritalStatus_Married           7830 non-null   bool
 33  MaritalStatus_Single            7830 non-null   bool
 34  MaritalStatus_Widowed           7830 non-null   bool
 35  HomeOwnershipStatus_Other       7830 non-null   bool
 36  HomeOwnershipStatus_Own         7830 non-null   bool
 37  HomeOwnershipStatus_Rent        7830 non-null   bool
 38  LoanPurpose_Debt Consolidation  7830 non-null   bool
 39  LoanPurpose_Education           7830 non-null   bool
 40  LoanPurpose_Home                7830 non-null   bool
 41  LoanPurpose_Other               7830 non-null   bool
 42  EmploymentStatus_Self-Employed  7830 non-null   bool
 43  EmploymentStatus_Unemployed     7830 non-null   bool
 44  EducationLevel_Bachelor         7830 non-null   bool
 45  EducationLevel_Doctorate        7830 non-null   bool
 46  EducationLevel_High School      7830 non-null   bool
 47  EducationLevel_Master           7830 non-null   bool
dtypes: bool(16), float64(32)
memory usage: 2.1 MB

In [16]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

# Создание модели Ridge с параметром регуляризации alpha (например, 1.0)
model = Ridge(alpha=1.0)
model.fit(X_train, y_train)

Ridge()

In [17]:
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 0.07075803261643929

In [18]:
def prepare_test_data(test_df, scaler, numeric_cols, categorical_cols):

    test_df = test_df.drop(columns=['ID', 'RiskScore'], errors='ignore')

    # Исключение 'RiskScore' из списка числовых признаков
    numeric_cols = numeric_cols.difference(['RiskScore'])

    # Конвертация ApplicationDate в datetime и разбиение на год, месяц и день
    test_df['ApplicationDate'] = pd.to_datetime(test_df['ApplicationDate'], errors='coerce')
    test_df['ApplicationYear'] = test_df['ApplicationDate'].dt.year
    test_df['ApplicationMonth'] = test_df['ApplicationDate'].dt.month
    test_df['ApplicationDay'] = test_df['ApplicationDate'].dt.day
    
    # Удаление исходного столбца
    test_df = test_df.drop(columns=['ApplicationDate'], errors='ignore')
    
    # One-hot encoding для категориальных признаков
    test_df = pd.get_dummies(test_df, columns=categorical_cols, drop_first=True)
    
    # Заполнение пропусков медианными значениями
    test_df.fillna(test_df.median(), inplace=True)
    
    # Приведение тестовых данных к тому же набору признаков, что и в тренировочных данных
    missing_cols = set(X_train.columns) - set(test_df.columns)
    for col in missing_cols:
        test_df[col] = 0  # Добавление недостающих столбцов
    
    # Убедимся, что порядок столбцов соответствует тренировочному набору
    test_df = test_df[X_train.columns]
    
    # Нормализация числовых признаков
    test_df[numeric_cols] = scaler.transform(test_df[numeric_cols])
    
    return test_df


# Использование функции для подготовки тестового набора
test_df = pd.read_csv('test.csv')  # Подставьте путь к тестовому набору
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          5000 non-null   int64
 1   ApplicationDate             5000 non-null   object
 2   Age                         5000 non-null   int64
 3   AnnualIncome                5000 non-null   int64
 4   CreditScore                 5000 non-null   int64
 5   LoanAmount                  5000 non-null   int64
 6   LoanDuration                5000 non-null   int64
 7   MaritalStatus               5000 non-null   object
 8   NumberOfDependents          5000 non-null   int64
 9   HomeOwnershipStatus         5000 non-null   object
 10  MonthlyDebtPayments         5000 non-null   int64
 11  CreditCardUtilizationRate   5000 non-null   float64
 12  NumberOfOpenCreditLines     5000 non-null   int64
 13  NumberOfCreditInquiries     5000 non-null   int64
 14  DebtToIncomeRatio           5000 non-null   float64
 15  BankruptcyHistory           5000 non-null   int64
 16  LoanPurpose                 5000 non-null   object
 17  PreviousLoanDefaults        5000 non-null   int64
 18  PaymentHistory              5000 non-null   int64
 19  LengthOfCreditHistory       5000 non-null   int64
 20  SavingsAccountBalance       5000 non-null   int64
 21  CheckingAccountBalance      5000 non-null   int64
 22  TotalAssets                 5000 non-null   int64
 23  TotalLiabilities            5000 non-null   int64
 24  MonthlyIncome               5000 non-null   float64
 25  UtilityBillsPaymentHistory  5000 non-null   float64
 26  JobTenure                   5000 non-null   int64
 27  EmploymentStatus            5000 non-null   object
 28  EducationLevel              5000 non-null   object
 29  Experience                  5000 non-null   int64
 30  NetWorth                    5000 non-null   int64
 31  BaseInterestRate            5000 non-null   float64
 32  InterestRate                5000 non-null   float64
 33  MonthlyLoanPayment          5000 non-null   float64
 34  TotalDebtToIncomeRatio      5000 non-null   float64
 35  LoanApproved                5000 non-null   int64
dtypes: float64(8), int64(22), object(6)
memory usage: 1.4+ MB

In [19]:
X_test_prepared = prepare_test_data(test_df, scaler, numeric_cols, categorical_cols)

# Предсказание с помощью модели
y_pred_normalized = model.predict(X_test_prepared)
# Делаем обратную нормализацию для получения Riskscore для изначальных ненормализованных значений
y_pred = scaler_risk.inverse_transform(y_pred_normalized.reshape(-1, 1))

In [20]:
y_pred

array([[33.5952309 ],
       [58.19662786],
       [30.41214231],
       ...,
       [62.06951205],
       [53.73182659],
       [86.02724572]])

In [21]:
# Преобразуем y_pred в одномерный массив
y_pred = y_pred.ravel()

# Создание DataFrame для отправки
submission = pd.DataFrame({'ID': test_df['ID'], 'RiskScore': y_pred})
submission.to_csv('submission.csv', index=False)